const brands=["Arçelik","Beko","Bosch","Siemens","Profilo","Vestel","Altus","Samsung","LG","Electrolux","Grundig","Regal","Miele","Diğer"];
const demoCodes=[
["Bosch","Çamaşır Makinesi","E18","Tahliye sistemi/pompa ile ilgili örnek kayıt."],
["Beko","Bulaşık Makinesi","E01","Örnek hata kaydı; model dokümanından doğrulanmalıdır."],
["Arçelik","Buzdolabı","E4","Örnek kayıt; model dokümanından doğrulanmalıdır."],
["Samsung","Çamaşır Makinesi","4E","Su besleme ile ilgili örnek kayıt."],
["LG","Çamaşır Makinesi","OE","Tahliye ile ilgili örnek kayıt."]
];
let services=JSON.parse(localStorage.getItem("tk_services")||"[]");
let parts=JSON.parse(localStorage.getItem("tk_parts")||JSON.stringify([{name:"Pompa",stock:3,price:950},{name:"Rezistans",stock:5,price:850}]));
let settings=JSON.parse(localStorage.getItem("tk_settings")||'{"name":"TEKNOTEM SERVİS","phone":"","vat":20,"travel":0}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(+n||0);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function persist(){localStorage.setItem("tk_services",JSON.stringify(services));localStorage.setItem("tk_parts",JSON.stringify(parts));localStorage.setItem("tk_settings",JSON.stringify(settings))}
function login(){if($("#loginUser").value&&$("#loginPass").value){localStorage.setItem("tk_login","1");$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#userBadge").textContent=$("#loginUser").value;renderAll()}}
function logout(){localStorage.removeItem("tk_login");location.reload()}
function nav(p){$$(".page").forEach(x=>x.classList.toggle("active",x.id===p));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));const t={dashboard:"Ana Panel",new:"Yeni Servis",customers:"Müşteriler",history:"Servisler",parts:"Stok / Parçalar",codes:"Arıza Kodları",reports:"Raporlar",settings:"Ayarlar"};$("#pageTitle").textContent=t[p];renderAll()}
$$(".nav").forEach(b=>b.onclick=()=>nav(b.dataset.page));
function calc(){const f=$("#serviceForm");if(!f)return;const d=new FormData(f),base=+d.get("parts")+ +d.get("labor")+ +d.get("travel"),tot=base*(1+(+d.get("vat")||0)/100);$("#total").textContent=money(tot)}
$("#serviceForm").addEventListener("input",calc);
$("#serviceForm").addEventListener("reset",()=>setTimeout(()=>{clearSignature();$("#photoPreview").innerHTML="";calc()},30));
let photoData="";
$("#photo").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{photoData=r.result;$("#photoPreview").innerHTML=`<img class="photo" src="${photoData}">`};r.readAsDataURL(f)});
$("#serviceForm").addEventListener("submit",e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const base=+d.parts+ +d.labor+ +d.travel;d.total=base*(1+(+d.vat||0)/100);d.id=Date.now();d.no="TK-"+new Date().getFullYear()+"-"+String(services.length+1).padStart(5,"0");d.date=new Date().toISOString();d.photo=photoData;d.signature=$("#signature").toDataURL();services.unshift(d);persist();alert("Servis kaydedildi: "+d.no);e.target.reset();photoData="";$("#photoPreview").innerHTML="";clearSignature();nav("history")});
const canvas=$("#signature"),ctx=canvas.getContext("2d");let drawing=false;
function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}
function start(e){drawing=true;ctx.beginPath();const p=pos(e);ctx.moveTo(p.x,p.y);e.preventDefault()}
function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}
function end(){drawing=false} canvas.addEventListener("pointerdown",start);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",end);canvas.addEventListener("pointerleave",end);
function clearSignature(){ctx.clearRect(0,0,canvas.width,canvas.height)}
function serviceRow(s){return `<div class="row"><div><strong>${esc(s.no)} • ${esc(s.customer)}</strong><small>${esc(s.brand)} • ${esc(s.category)} • ${esc(s.model||"-")} • ${new Date(s.date).toLocaleDateString("tr-TR")} <span class="status">${esc(s.status)}</span></small></div><div><span class="pill">${money(s.total)}</span> <button class="ghost" onclick="printService(${s.id})">PDF</button></div></div>`}
function renderDash(){$("#statServices").textContent=services.length;$("#statOpen").textContent=services.filter(s=>!["Tamamlandı","İptal"].includes(s.status)).length;$("#statCustomers").textContent=new Set(services.map(s=>s.customer.toLowerCase())).size;$("#statRevenue").textContent=money(services.reduce((a,s)=>a+(+s.total||0),0));$("#recent").innerHTML=services.slice(0,6).map(serviceRow).join("")||'<div class="empty">Henüz servis yok.</div>'}
function renderHistory(){const q=($("#historySearch")?.value||"").toLowerCase();$("#historyList").innerHTML=services.filter(s=>(s.no+" "+s.customer+" "+s.brand+" "+s.model).toLowerCase().includes(q)).map(serviceRow).join("")||'<div class="empty">Kayıt bulunamadı.</div>'}
function renderCustomers(){const q=($("#customerSearch")?.value||"").toLowerCase();const names=[...new Set(services.map(s=>s.customer))].filter(n=>n.toLowerCase().includes(q));$("#customerList").innerHTML=names.map(n=>{const a=services.filter(s=>s.customer===n),s=a[0];return `<div class="row"><div><strong>${esc(n)}</strong><small>${esc(s.phone)} • ${esc(s.address)}<br>${a.length} servis • Son cihaz: ${esc(s.brand)} ${esc(s.category)}</small></div><span class="pill">${money(a.reduce((x,y)=>x+(+y.total||0),0))}</span></div>`}).join("")||'<div class="empty">Müşteri bulunamadı.</div>'}
function renderParts(){$("#partsList").innerHTML=parts.map((p,i)=>`<div class="row"><div><strong>${esc(p.name)}</strong><small>Stok: ${p.stock} • Birim: ${money(p.price)}</small></div><div><button class="ghost" onclick="changeStock(${i},-1)">−</button> <button class="ghost" onclick="changeStock(${i},1)">+</button></div></div>`).join("")}
function addPart(){const n=prompt("Parça adı");if(!n)return;const stock=+prompt("Stok",1)||0,price=+prompt("Birim fiyat",0)||0;parts.push({name:n,stock,price});persist();renderParts()}
function changeStock(i,d){parts[i].stock=Math.max(0,parts[i].stock+d);persist();renderParts()}
function renderCodes(){const q=($("#codeSearch")?.value||"").toLowerCase();$("#codeList").innerHTML=demoCodes.filter(x=>x.join(" ").toLowerCase().includes(q)).map(x=>`<div class="row"><div><strong>${esc(x[0])} • ${esc(x[1])} • ${esc(x[2])}</strong><small>${esc(x[3])}</small></div></div>`).join("")||'<div class="empty">Kod bulunamadı.</div>'}
function renderReports(){const total=services.reduce((a,s)=>a+(+s.total||0),0),done=services.filter(s=>s.status==="Tamamlandı").length;$("#reportGrid").innerHTML=`<div class="report"><b>Toplam Ciro</b><strong>${money(total)}</strong></div><div class="report"><b>Tamamlanan</b><strong>${done}</strong></div><div class="report"><b>Açık Servis</b><strong>${services.length-done}</strong></div>`}
function renderSettings(){$("#setName").value=settings.name;$("#setPhone").value=settings.phone;$("#setVat").value=settings.vat;$("#setTravel").value=settings.travel}
function saveSettings(){settings={name:$("#setName").value,phone:$("#setPhone").value,vat:+$("#setVat").value||0,travel:+$("#setTravel").value||0};persist();alert("Ayarlar kaydedildi")}
function exportBackup(){const blob=new Blob([JSON.stringify({services,parts,settings},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="teknotem-yedek-"+new Date().toISOString().slice(0,10)+".json";a.click()}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);services=x.services||[];parts=x.parts||[];settings=x.settings||settings;persist();renderAll();alert("Yedek yüklendi")}catch{alert("Geçersiz yedek")}};r.readAsText(f)}
function printReport(){const w=open("","_blank");w.document.write(`<html><body style="font-family:Arial;margin:40px"><h1>${esc(settings.name)}</h1><h2>Servis Raporu</h2><p>Toplam servis: ${services.length}</p><p>Toplam ciro: ${money(services.reduce((a,s)=>a+(+s.total||0),0))}</p><p>Tamamlanan: ${services.filter(s=>s.status==="Tamamlandı").length}</p><script>print()<\/script></body></html>`);w.document.close()}
window.printService=function(id){const s=services.find(x=>x.id===id);if(!s)return;const w=open("","_blank");w.document.write(`<html lang="tr"><head><meta charset="UTF-8"><title>${esc(s.no)}</title><style>body{font-family:Arial;margin:32px;color:#111}.top{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:14px}h1{margin:0}.box{border:1px solid #bbb;padding:12px;margin:12px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.label{font-size:10px;color:#666}.v{font-weight:bold;margin:4px 0}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:8px}.total{text-align:right;font-size:20px;font-weight:bold;margin:15px 0}.sign{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:60px}.photo{max-width:250px}@media print{button{display:none}}</style></head><body><div class="top"><div><h1>${esc(settings.name)}</h1><div>TEKNİK SERVİS FORMU</div></div><div><b>${esc(s.no)}</b><br>${new Date(s.date).toLocaleString("tr-TR")}</div></div><div class="box grid"><div><div class="label">MÜŞTERİ</div><div class="v">${esc(s.customer)}</div>${esc(s.phone)}<br>${esc(s.address)}</div><div><div class="label">CİHAZ</div><div class="v">${esc(s.brand)} • ${esc(s.category)}</div>Model: ${esc(s.model)}<br>Seri No: ${esc(s.serial)}<br>Garanti: ${esc(s.warranty)}</div></div><div class="box"><b>Şikâyet</b><p>${esc(s.complaint)}</p><b>Tespit</b><p>${esc(s.diagnosis)}</p><b>Yapılan İşlem</b><p>${esc(s.work)}</p><b>Arıza Kodu:</b> ${esc(s.code||"-")}</div><table><tr><th>Kalem</th><th>Tutar</th></tr><tr><td>Parça</td><td>${money(s.parts)}</td></tr><tr><td>İşçilik</td><td>${money(s.labor)}</td></tr><tr><td>Servis</td><td>${money(s.travel)}</td></tr><tr><td>KDV</td><td>%${esc(s.vat)}</td></tr></table><div class="total">GENEL TOPLAM: ${money(s.total)}</div>${s.photo?`<img class="photo" src="${s.photo}">`:""}<div class="box">Bu belge ${esc(settings.name)} tarafından oluşturulan servis kaydıdır; üretici adına düzenlenmiş resmi yetkili servis belgesi değildir.</div><div class="sign"><div>Müşteri Onayı / İmza<br>${s.signature?`<img src="${s.signature}" style="max-width:260px">`:""}</div><div>Teknisyen / İmza</div></div><script>print()<\/script></body></html>`);w.document.close()};
function renderAll(){renderDash();renderHistory();renderCustomers();renderParts();renderCodes();renderReports();renderSettings()}
$("#historySearch").oninput=renderHistory;$("#customerSearch").oninput=renderCustomers;$("#codeSearch").oninput=renderCodes;
$("#brand").innerHTML=brands.map(x=>`<option>${x}</option>`).join("");
$("#serviceForm").querySelector('[name="vat"]').value=settings.vat;$("#serviceForm").querySelector('[name="travel"]').value=settings.travel;calc();
if(localStorage.getItem("tk_login")==="1"){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#userBadge").textContent="admin";renderAll()}
